services:
  pg:
    image: postgres:18.0
    restart: always
    environment:
      POSTGRES_USER: "cdynot"
      POSTGRES_PASSWORD: "parol"
      POSTGRES_DB: "weather"
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}